### ISSUE TITLE
Application Failing with these settings

### ISSUE THREAD

**Issue by aminaaslam** [ywilkof/spark-jobs-rest-client#4]
Hi there,
Whenever i try to submit my application with following properties, application fails i.e. its state is "Failed" on the spark UI. Please help me sort this out.

final String submissionId=sparkRestClient.prepareJobSubmit().appName("MySparkJobs-SparkPi")
					.appResource("/usr/local/spark/examples/jars/spark-examples_2.11-2.0.0.jar").mainClass("org.apache.spark.examples.SparkPi")
					.withProperties()
					.put("spark.eventLog.enabled", "true")
					.put("spark.dynamicAllocation.enabled","true")
					.put("spark.shuffle.service.enabled","true")
					.submit();

**Comment by aminaaslam** [comment]
ywilkof this is the issue that i am encountering please look into it.

**Comment by ywilkof** [comment]
Hi @aminaaslam,
Without any logging from the driver/executors I unfortunately cannot help or determine whether this is a problem with this submit client or your job, though the fact that the job appears in the UI  means the submit of the client was successful. In order to isolate the issue, please attach the error message.

**Comment by aminaaslam** [comment]
I was able to fix it by looking the the log files. But i have another question which i will ask in a separate thread.
